whitelist_rules:
  - block_based_kvo
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - discarded_notification_center_observer
  - colon
  - comma
  - conditional_returns_on_newline
  - control_statement
  - custom_rules
  - cyclomatic_complexity
  - empty_enum_arguments
  - empty_count
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  #- file_length
  - fatal_error_message
  - force_try
  - function_body_length
  - function_parameter_count
  - implicit_getter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  #- multiline_arguments
  - opening_brace
  - operator_usage_whitespace
  - overridden_super_call
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_nil_coalescing
  - redundant_string_enum_value
  - return_arrow_whitespace
  - statement_position
  - superfluous_disable_command
  - syntactic_sugar
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  #- type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_enumerated
  - valid_ibinspectable
  - void_return
  - weak_delegate
  - xctfail_message

custom_rules:
  invalid_square_brace_whitespaces:
    name: "Square bracket without whitespaces"
    regex: '([^"]\[[ \t]+[\S]|[\S][ \t]+\][^"])'
    match_kinds:
      - argument
      - attribute.builtin
      - attribute.id
      - buildconfig.id
      - buildconfig.keyword
      - identifier
      - keyword
      - number
      - objectliteral
      - parameter
      - placeholder
      - string
      - string_interpolation_anchor
      - typeidentifier
    message: "Square brackets should not contain whitespaces after opening bracket and before the closing one."
    severity: warning

excluded:
  - Pods
  - vendor

statement_position:
  statement_mode: uncuddled_else
  severity: warning
function_body_length:
  warning: 60
  error: 100
file_length:
  warning: 300
  error: 1393
cyclomatic_complexity:
  warning: 10
  error: 20
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50

reporter: "xcode"

